data:
  path_basic_df : ../input/m5-forecasting-accuracy/sales_train_evaluation_basic.csv
  path_test_df : ../input/m5-forecasting-accuracy/test_basic.csv

feat:
  lag_win_pairs: [[28, 28],[28, 7],[7,7],[7, 3],[1, 3]]

lgbm:
  optuna_tuning : False
  pretrained : False
  pretrained_model_path : ""
  model_params:
    objective : tweedie
    # objective : poisson
    tweedie_variance_power : 1.1
    # metric : ["custom", "rmse"]
    metric : rmse
    learning_rate : 0.05
    feature_fraction: 0.8
    bagging_fraction : 0.85
    bagging_freq : 1
    lambda_l2 : 0.1
    num_leaves: 40
    min_data_in_leaf: 100
    max_depth : -1
    num_threads : 8

  train_params:
    num_boost_round : 2000
    early_stopping_rounds : 200
