data:
  path_basic_df : "../input/m5-forecasting-accuracy/sales_train_evaluation_basic.csv"

lgbm:
  tuning : True
  model_params:
    objective : tweedie
    tweedie_variance_power : 1.1
    # metric : ["custom", "rmse"]
    metric : ["rmse"]
    learning_rate : 0.08
    feature_fraction: 0.6
    bagging_fraction : 0.85
    bagging_freq : 1
    lambda_l2 : 0.1
    num_leaves: 70
    min_data_in_leaf: 100
    max_depth : 7
    num_threads : 8
    # {
    # "objective" : "tweedie",
    # "tweedie_variance_power" : 1.1,
    # "metric" : ["custom", "rmse"],
    # "learning_rate" : 0.08,
    # "feature_fraction": 0.6,
    # "bagging_fraction" : 0.85,
    # "bagging_freq" : 1,
    # "lambda_l2" : 0.1,
    # "num_leaves": 70,
    # "min_data_in_leaf": 100,
    # "max_depth" : 7,
    # "num_threads": 8,}
  train_params:
    num_boost_round : 2500
    early_stopping_rounds : 500
